server:
  port: 8200
spring:
  application:
    name: @artifactId@
logging:
  level:
    root: info
    com.hp: debug

dingtalk:
  miniH5:
    event:
      listener:
        enabled: true
      enabled: true
